//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scorto.DocAnalysis.WebService.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestData", Namespace="http://schemas.datacontract.org/2004/07/Scorto.DocAnalysis.WebService.Models")]
    public partial struct RequestData : System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DataField;
        
        private string DescriptionField;
        
        private bool SendProcessedImageField;
        
        private bool UseDemoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SendProcessedImage
        {
            get
            {
                return this.SendProcessedImageField;
            }
            set
            {
                this.SendProcessedImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseDemo
        {
            get
            {
                return this.UseDemoField;
            }
            set
            {
                this.UseDemoField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IImageForgeryDetector")]
public interface IImageForgeryDetector
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageForgeryDetector/SubmitImage", ReplyAction="http://tempuri.org/IImageForgeryDetector/SubmitImageResponse")]
    string SubmitImage(Scorto.DocAnalysis.WebService.Models.RequestData data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageForgeryDetector/CheckStatus", ReplyAction="http://tempuri.org/IImageForgeryDetector/CheckStatusResponse")]
    string CheckStatus(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageForgeryDetector/GetResults", ReplyAction="http://tempuri.org/IImageForgeryDetector/GetResultsResponse")]
    string GetResults(string id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IImageForgeryDetectorChannel : IImageForgeryDetector, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ImageForgeryDetectorClient : System.ServiceModel.ClientBase<IImageForgeryDetector>, IImageForgeryDetector
{
    
    public ImageForgeryDetectorClient()
    {
    }
    
    public ImageForgeryDetectorClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ImageForgeryDetectorClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ImageForgeryDetectorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ImageForgeryDetectorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string SubmitImage(Scorto.DocAnalysis.WebService.Models.RequestData data)
    {
        return base.Channel.SubmitImage(data);
    }
    
    public string CheckStatus(string id)
    {
        return base.Channel.CheckStatus(id);
    }
    
    public string GetResults(string id)
    {
        return base.Channel.GetResults(id);
    }
}
